name: Build and publish

on:
  workflow_dispatch:

jobs:
  BuildAndPublish:
    runs-on: windows-latest
    steps:
      - name: 'Clone the Urho 3D repo'
        run: |
          git clone https://github.com/urho3d/Urho3D

      - name: 'Run cmake against the root of the repo'
        run: |
          cd Urho3D
          cmake -S . -B build
          cmake --build build
      
      - name: 'Upload resulted binaries'
        uses: actions/upload-artifact@v2
        with:
          name: binaries-x64
          path: ./Urho3D/build
          retention-days: 5
